languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "HoNK HOnK"
contentDir = 'content/zh-cn'

[params]
  displayName = "中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006年1月2日"
  logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "一只野鹅嘎嘎嘎嘎"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Snow Goose"
  image = "img/avatar.png"
  headline = "闭院开轩笑语阑，江山并入一壶宽。"
  bio = "一只野鹅"
  links = [
    { email = "mailto:snowgoose0818@gmail.com" },
    { github = "https://github.com/GreatSnowGoose" },
  ]
